import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/Header/page.jsx"; 
import Boost from "./component/Boost/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {/* <Boost/> */}
        <div>
        {children}
        </div>
        </body>
    </html>
  );
}
